### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by BrandonSmith** [zoho/react-native-zohodesk-portal-sdk#1]
Building produces the following error:

Showing Recent Errors Only
/Users/brandon/work/rw/releases/zoho/relay/node_modules/react-native-zohodesk-portal-sdk/ios/RNZDPortalSubmitTicket.m:22:6: Unknown receiver 'ZDPortalSubmitTicket'; did you mean 'RNZDPortalSubmitTicket'?

Showing Recent Errors Only
/Users/brandon/work/rw/releases/zoho/relay/node_modules/react-native-zohodesk-portal-sdk/ios/RNZDPortalSubmitTicket.m:22:27: No known class method for selector 'showWithTitle:navigationMode:'

Showing Recent Errors Only
/Users/brandon/work/rw/releases/zoho/relay/node_modules/react-native-zohodesk-portal-sdk/ios/RNZDPortalSubmitTicket.m:22:60: Use of undeclared identifier 'ZDPNavigationModePresent'

**Comment by Bala-Karunakaran** [comment]
Hi @BrandonSmith Please draft the issues with maximum information and share the details to "support@zohodesk.com". We shall take this forward.

Thanks.

**Comment by eduardoleal** [comment]
Hello @BrandonSmith, were you able to solve this issue?

**Comment by Bala-Karunakaran** [comment]
Hi @eduardoleal ,

Somehow the references did not update in the Podfile.lock.
Please follow the below steps
- pod cache clean --all
- pod repo update
Also, please make sure that Podfile.lock file is updated. Try to remove it, run pod install, and check.

Should you have any queries, feel free to hit us up at support@zohodesk.com

**Comment by gbarany** [comment]
@Bala-Karunakaran, I've followed the steps above, but still facing the same issue
<img width="695" alt="image" src="https://user-images.githubusercontent.com/23645175/183647552-459b2d3c-3b2a-48f6-954b-cf58b41a202a.png">

**Comment by expouic** [comment]
Same issue here! 
Do you have a solution for that?

**Comment by expouic** [comment]
Do you try the version 1.0.4? Works for me…
