### ISSUE TITLE
i am getting No known class method for selector 'showWithTitle:navigationMode:' while building the react native project in mac m1

### ISSUE THREAD

**Issue by Vishnu-swindia** [zoho/react-native-zohodesk-portal-sdk#13]
No known class method for selector 'showWithTitle:navigationMode:'
Use of undeclared identifier 'ZDPNavigationModePresent'
<img width="1470" alt="Screenshot 2023-05-22 at 11 38 23 AM" src="https://github.com/zoho/react-native-zohodesk-portal-sdk/assets/114577176/a9ccdabd-97f8-430a-bd4e-1e651210327f">

i am using react-native-zohoportal-sdk@1.0.7 , i have updated to latest version too, still getting the same error , tried all the solution out there.. please help...

**Comment by Bala-Karunakaran** [comment]
Hi @Vishnu-swindia ,

The class name mismatched in the screenshot you shared. Its not  RNZDPortalTickets, its ZDPortalTicket. You can verify the code snippet [here](https://github.com/zoho/react-native-zohodesk-portal-sdk/blob/master/ios/RNZDPortalTickets.m)

Can you please check with our latest version 1.2.1. 

Still you face issues, I'd suggest reaching out to us at [support@zohodesk.com](mailto:support@zohodesk.com) with maximum information.

Thanks.
