### ISSUE TITLE
Build failed while using react-native-zohodesk-portal-sdk in iOS

### ISSUE THREAD

**Issue by selvamariappant2s** [zoho/react-native-zohodesk-portal-sdk#14]
Build Failed while using  react-native-zohodesk-portal-sdk 

Syntax error in RNZohoDeskPortalSDK.m

COMPILATION ISSUE 

/Users/runner/work/1/s/node_modules/react-native-zohodesk-portal-sdk/ios/RNZohoDeskPortalSDK.m:68:37: error: expected ')'
                  isJWTToken: (BOOL isSuccess))
                                    ^
/Users/runner/work/1/s/node_modules/react-native-zohodesk-portal-sdk/ios/RNZohoDeskPortalSDK.m:68:31: note: to match this '('
                  isJWTToken: (BOOL isSuccess))
                              ^

**Comment by selvamariappant2s** [comment]
In Recent Update Following method changed 

RCT_EXPORT_METHOD(setUserToken:(NSString *)userToken
                  successCallback:(RCTResponseSenderBlock)successCallback
                  errorCallback:(RCTResponseSenderBlock)errorCallback)
{

   [ZohoDeskPortalSDK loginWithUserToken:userToken onCompletion:^(BOOL isSuccess) {
        if (isSuccess){
            successCallback(@[[NSString stringWithFormat:@"User set Success"], @"User set Success"]);
        }else{
            errorCallback(@[[NSString stringWithFormat:@"User set Failure"], @"User set Failure"]);
        }
    }];
}

Change to 

RNZohoDeskPortalSDK.m

RCT_EXPORT_METHOD(setUserToken:(NSString *)userToken
                  successCallback:(RCTResponseSenderBlock)successCallback
                  errorCallback:(RCTResponseSenderBlock)errorCallback
                  isJWTToken: (BOOL isSuccess))
{
    [ZohoDeskPortalSDK loginWithUserToken:userToken onCompletion:^(BOOL isSuccess) {
        if (isSuccess){
            successCallback(@[[NSString stringWithFormat:@"User set Success"], @"User set Success"]);
        }else{
            errorCallback(@[[NSString stringWithFormat:@"User set Failure"], @"User set Failure"]);
        }
    }];
}

**Comment by selvamariappant2s** [comment]
Temp Soultion 

using patch-package npm to slove below patch 

react-native-zohodesk-portal-sdk+1.2.2.patch

`diff --git a/node_modules/react-native-zohodesk-portal-sdk/ios/RNZohoDeskPortalSDK.m b/node_modules/react-native-zohodesk-portal-sdk/ios/RNZohoDeskPortalSDK.m
index e9aeda8..e1b9074 100644
--- a/node_modules/react-native-zohodesk-portal-sdk/ios/RNZohoDeskPortalSDK.m
+++ b/node_modules/react-native-zohodesk-portal-sdk/ios/RNZohoDeskPortalSDK.m
@@ -64,8 +64,7 @@ - (dispatch_queue_t)methodQueue

 RCT_EXPORT_METHOD(setUserToken:(NSString *)userToken
                   successCallback:(RCTResponseSenderBlock)successCallback
-                  errorCallback:(RCTResponseSenderBlock)errorCallback
-                  isJWTToken: (BOOL isSuccess))
+                  errorCallback:(RCTResponseSenderBlock)errorCallback)
 {
     [ZohoDeskPortalSDK loginWithUserToken:userToken onCompletion:^(BOOL isSuccess) {
         if (isSuccess){
`

**Comment by Bala-Karunakaran** [comment]
Hi @selvamariappant2s ,

We have fixed the issue in version-1.2.3. Please check it out.
