### ISSUE TITLE
push notification not work on iphone 8

### ISSUE THREAD

**Issue by hieplam** [zoho/react-native-zohodesk-portal-sdk#2]
I'm following this [document](https://help.zoho.com/portal/en/kb/desk/for-developers/asap/react-native-sdk/articles/working-with-the-asap-sdk-for-react-native#Step_1_Create_a_mobile_add-on_in_Zoho_Desk) from *step 1* to *step 7* to config push notification when user let the app in background

Everything config properly (include setting in desk Zoho, upload .p12 file) 
I've tried to start a chat from mobile device and an help desk answer. It work fine. 

However when i let the app in background by press home button. or just kill app and open again. my app wont receive notification when help desk answer

i've created a repo here for demo, https://github.com/hieplam/zohotest please change your `Zoho_ID`, `Org_ID` in `App.js`

i'm looking for your reply, thanks

**Comment by hieplam** [comment]
any update?

**Comment by Bala-Karunakaran** [comment]
Hi @hieplam 

I see one of the support reps has assisted you in ticket #71867061. Hope that helps. Should you have any queries please hit us up at support@zohodesk.com.
