### ISSUE TITLE
Could not find com.zoho.desk:asapsdk:3.0_BETA_22.

### ISSUE THREAD

**Issue by dixitU** [zoho/react-native-zohodesk-portal-sdk#21]
After installing react-native-zohodesk-portal-sdk using yarn

**yarn add react-native-zohodesk-portal-sdk**

react-native version 0.72.3
react-native-zohodesk-portal-sdk version 1.3.6

try to run project using **npx react-native run-android**. facing this issue

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-zohodesk-portal-sdk:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-zohodesk-portal-sdk:debugCompileClasspath'.
   > Could not find com.zoho.desk:asapsdk:3.0_BETA_22.
     Required by:
         project :react-native-zohodesk-portal-sdk

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

What should i do?

**Comment by vignesthillai** [comment]
Hi @dixitU  As we discussed over Support Channel, Zoho's maven urls need to be configured in the project-level build.gradle file. That will resolve the issue
