### ISSUE TITLE
can you please tell how can we customize using RNZohodeskPortalSDK.setThemeResource(resourceId) 

### ISSUE THREAD

**Issue by Vishnu-swindia** [zoho/react-native-zohodesk-portal-sdk#7]

**Comment by mohanrajds** [comment]
@Vishnu-swindia   Please Look into our document for the theme customization 

https://help.zoho.com/portal/en/kb/desk/for-developers/asap/react-native-sdk/articles/working-with-the-asap-sdk-for-react-native#Step_8_Customize_the_theme_of_the_add-on

Please write to us if you need more clarification.
