### ISSUE TITLE
Need Help with setting up RN project on Mac for iOS build.

### ISSUE THREAD

**Issue by VinayakGupta5** [zoho/react-native-zohodesk-portal-sdk#9]
<img width="1394" alt="Screenshot 2022-11-15 at 1 28 15 PM" src="https://user-images.githubusercontent.com/87755067/201862099-0bdcc58b-0710-478b-a81a-119fcb3e35d7.png">

Please assist with this error.
 
There are a lot of warnings to regarding deployment version.

feel free to contact me at vinayakgupta@swindia.com

**Comment by Iamdhammi** [comment]
@VinayakGupta5 were you able to fix this? I'm facing the same issues.

**Comment by Bala-Karunakaran** [comment]
This issue not persist in latest version. Kindly check and update.

Still you face the issue, I'd suggest reaching out to us at [support@zohodesk.com](mailto:support@zohodesk.com) with maximum information.

Thanks.
